# Generated by Django 5.0.3 on 2024-03-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=100)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("room_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TacoEntrance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("status", models.IntegerField(default=0)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dasite.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dasite.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dong_time", models.DateTimeField(auto_now_add=True)),
                ("dong_type", models.IntegerField(default=0)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dasite.location",
                    ),
                ),
                (
                    "dongee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dongee",
                        to="dasite.user",
                    ),
                ),
                (
                    "donger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donger",
                        to="dasite.user",
                    ),
                ),
            ],
        ),
    ]
