# Generated by Django 5.0.3 on 2024-04-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dasite", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="room_id",
            new_name="room",
        ),
    ]
