# Generated by Django 5.0.3 on 2024-03-31 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dasite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dongable",
            fields=[
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="dasite.user",
                    ),
                ),
                ("can_dong", models.BooleanField(default=True)),
            ],
        ),
    ]
