# Generated by Django 5.0.3 on 2024-03-31 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dasite", "0002_dongable"),
    ]

    operations = [
        migrations.AddField(
            model_name="dongable",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dongable",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dasite.user",
                unique=True,
            ),
        ),
    ]
