# Generated by Django 5.0.3 on 2024-03-31 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dasite", "0005_dongable_id_alter_dongable_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dongable",
            name="id",
        ),
        migrations.AlterField(
            model_name="dongable",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="dasite.user",
            ),
        ),
    ]
